name: bot-doublej
run-name: Bot (Double J)

on:
  schedule:
    - cron: '*/5 * * * *' # Run every two minutes
  workflow_dispatch: # Manual run trigger

    
jobs:
  scrape:
    runs-on: ubuntu-latest
    environment: Double J
    
    env:
      STATION: ${{ vars.STATION }}
      TIMEZONE: ${{ vars.TIMEZONE }}
      BSKY_HANDLE: ${{ vars.BSKY_HANDLE }}
      BSKY_USERNAME: ${{ secrets.BSKY_USERNAME }}
      BSKY_PASSWORD: ${{ secrets.BSKY_PASSWORD }}
      SPOTIFY_CLIENT: ${{ secrets.SPOTIFY_CLIENT }}
      SPOTIFY_SECRET: ${{ secrets.SPOTIFY_SECRET }}
     
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        
      - name: Create .env
        uses: iamsauravsharma/create-dotenv@v2.0.1
        
      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version: 18
        
      - uses: pnpm/action-setup@v3
        name: Install pnpm
        with:
          version: 8
          run_install: false

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - uses: actions/cache@v4
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install   
        
      - name: Scrape!
        run: pnpm scrape