name: scrape-and-post
run-name: Scrape and post

on:
  - push

#on:
#  schedule:
#    - cron: "*/1.5 * * * *"

env:
  ENV_USERNAME: ${{ secrets.USERNAME }}
  ENV_PASSWORD: ${{ secrets.PASSWORD }}
  ENV_TIMEZONE: ${{ vars.TIMEZONE }}
  ENV_SPOTIFY_CLIENT: ${{ secrets.SPOTIFY_CLIENT }}
  ENV_SPOTIFY_SECRET: ${{ secrets.SPOTIFY_SECRET }}
    
jobs:
  scrape:
    runs-on: ubuntu-latest
     
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        
      - name: Create .env
        uses: CallePuzzle/envvar-to-dotenv-action@0.1.0
        with:
          variableNamesByFilter: ^ENV_.*
        
      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version: 18
        
      - uses: pnpm/action-setup@v3
        name: Install pnpm
        with:
          version: 8
          run_install: false

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install   
        
      - name: Scrape!
        run: pnpm scrape  